
name: Check for Eurostar Tickets

on:
  workflow_dispatch:

  schedule:
    # Runs every 10 minutes, except from midnight to 6am Paris time (22:00-04:00 UTC)
    - cron: '*/10 4-22 * * *'

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: python check_tickets.py
